/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fatec.poo.View;

import Fatec.poo.model.Pedido;
import Fatec.poo.model.Pessoa;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author gdeba
 */
public class GuiConsultaClientePedido extends javax.swing.JFrame {
    MaskFormatter mcpf;
    
    /**
     * Creates new form GuiCadastrarCliente
     */
    public GuiConsultaClientePedido(ArrayList <Pedido> cadPedidos) throws ParseException {
        mcpf = new MaskFormatter("###.###.###-##");
        initComponents();
        cadastroPedido = cadPedidos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldnome = new javax.swing.JTextField();
        jFormattedTextFieldcpfcliente = new javax.swing.JFormattedTextField(mcpf);
        ;
        jTextFieldlimitedisp = new javax.swing.JTextField();
        jTextFieldtotalpedidos = new javax.swing.JTextField();
        jTextFieldlimitecred = new javax.swing.JTextField();
        jTextFieldqtdpedidos = new javax.swing.JTextField();
        jButtonconsultar = new javax.swing.JButton();
        jButtonsair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldnome.setEnabled(false);

        jTextFieldlimitedisp.setEnabled(false);

        jTextFieldtotalpedidos.setEnabled(false);

        jTextFieldlimitecred.setEnabled(false);

        jTextFieldqtdpedidos.setEnabled(false);

        jButtonconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fatec/poo/View/icons/Consultar.png"))); // NOI18N
        jButtonconsultar.setText("Consultar");
        jButtonconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconsultarActionPerformed(evt);
            }
        });

        jButtonsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fatec/poo/View/icons/Sair.png"))); // NOI18N
        jButtonsair.setText("Sair");
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF");

        jLabel2.setText("Limite Crédito");
        jLabel2.setEnabled(false);

        jLabel3.setText("Qtde.Pedidos");
        jLabel3.setEnabled(false);

        jLabel4.setText("Limite Disponível");
        jLabel4.setEnabled(false);

        jLabel5.setText("TotalPedidos");
        jLabel5.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldlimitecred)
                        .addComponent(jTextFieldqtdpedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFormattedTextFieldcpfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldlimitedisp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldtotalpedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonconsultar)
                .addGap(64, 64, 64)
                .addComponent(jButtonsair, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldcpfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldlimitecred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldlimitedisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldqtdpedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtotalpedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonconsultar)
                    .addComponent(jButtonsair))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconsultarActionPerformed
        DecimalFormat df = new DecimalFormat("#,##0.00");
        int qtd = 0;
        double total = 0;
        int x,aux = 0;
        boolean existe = Pessoa.verificaCPF(jFormattedTextFieldcpfcliente.getText());
        if(!existe){
            JOptionPane.showMessageDialog(null, "CPF inválido");
            jFormattedTextFieldcpfcliente.setText(null);
        }
        else{
        for(x = 0; x < cadastroPedido.size();x++){
            if(cadastroPedido.get(x).getCliente().getCpf().equals(jFormattedTextFieldcpfcliente.getText())){
                qtd++;
            }
            if(qtd == 1){
                jTextFieldnome.setText(cadastroPedido.get(x).getCliente().getNome());
                aux = x;
            }
        }
        if(qtd > 0){
            jTextFieldlimitecred.setText("R$"+String.valueOf(df.format(cadastroPedido.get(aux).getCliente().getLimiteCredito())));
            jTextFieldlimitedisp.setText("R$"+String.valueOf(df.format(cadastroPedido.get(aux).getCliente().getLimiteDisponivel())));
            jTextFieldqtdpedidos.setText(String.valueOf(qtd));
            jTextFieldtotalpedidos.setText("R$"+String.valueOf(df.format(cadastroPedido.get(aux).getCliente().getLimiteCredito() - cadastroPedido.get(aux).getCliente().getLimiteDisponivel())));
        }
        else{
            JOptionPane.showMessageDialog(null, "Cliente Inexistente");
        }
      }
    }//GEN-LAST:event_jButtonconsultarActionPerformed

    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiConsultaClientePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiConsultaClientePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiConsultaClientePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiConsultaClientePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonconsultar;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JFormattedTextField jFormattedTextFieldcpfcliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldlimitecred;
    private javax.swing.JTextField jTextFieldlimitedisp;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldqtdpedidos;
    private javax.swing.JTextField jTextFieldtotalpedidos;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pedido> cadastroPedido;
    private int posFuncPedido;

}
