/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fatec.poo.View;

import Fatec.poo.model.Cliente;
import Fatec.poo.model.ItemPedido;
import Fatec.poo.model.Pedido;
import Fatec.poo.model.Pessoa;
import Fatec.poo.model.Produto;
import Fatec.poo.model.Vendedor;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author gdeba
 */
public class GuiEmitirPedido extends javax.swing.JFrame {
     MaskFormatter mdata;
     MaskFormatter mcpf;
     int sequencia;
     int i = 0;
     Pedido pedido;
     double limite;
    /**
     * Creates new form EmitirPedido
     * @param cadPessoa
     * @param cadProdutos
     * @param cadPedidos
     * @throws java.text.ParseException
     */
    public GuiEmitirPedido(ArrayList <Pessoa> cadPessoa, ArrayList <Produto> cadProdutos,ArrayList <Pedido> cadPedidos) throws ParseException {
        mdata = new MaskFormatter("##/##/####");
        mcpf = new MaskFormatter("###.###.###-##");
        initComponents();
        cadastroProd = cadProdutos;
        cadastro = cadPessoa;
        cadastroPedido = cadPedidos;
        String[] relProd;
        
        
        relProd = listarProdutos();
        jComboBoxprodutos.addItem("");
        for (int x=0; x < relProd.length; x++){
            jComboBoxprodutos.addItem(relProd[x]);
        }
        
    }
    
    private String[] listarProdutos(){
        String[] listaProd = new String[cadastroProd.size()];
        
        for (int x=0; x < cadastroProd.size(); x++){
            listaProd[x] = cadastroProd.get(x).getCodigo();
        
       }
        return listaProd;
    }
    
    public void alteraComponentes(){
        DefaultTableModel modTblPedido = (DefaultTableModel)jTablepedido.getModel();
        jTextFieldnumPedido.setText(null);
        jFormattedTextFieldcpfcliente.setText(null);
        jFormattedTextFieldcpfvendedor.setText(null);
        jFormattedTextFielddatapedido.setText(null);
        jTextFieldqtditenspedidos.setText(null);
        jTextFieldqtdvendida.setText(null);
        jTextFieldvalTotalPedido.setText(null);
        jComboBoxformaspagamento.setSelectedIndex(0);
        jComboBoxprodutos.setSelectedIndex(0);
        while (modTblPedido.getRowCount()>0) { modTblPedido.removeRow(0); }
        jFormattedTextFieldcpfcliente.setEnabled(false);
        jFormattedTextFieldcpfvendedor.setEnabled(false);
        jFormattedTextFielddatapedido.setEnabled(false);
        jButtoninseriritem.setEnabled(false);
        jButtonremoveritem.setEnabled(false);
        jTextFieldnumPedido.setEnabled(true);
        jButtonverificapedido.setEnabled(true);
        jButtonverificavendedor.setEnabled(false);
        jButtonverificacliente.setEnabled(false);
        jButtonverificaproduto.setEnabled(false);
        jButtonalterar.setEnabled(false);
        jButtoninsert.setEnabled(false);
        jButtondelete.setEnabled(false);
        jComboBoxprodutos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldnomecliente1 = new javax.swing.JTextField();
        jFormattedTextFieldcpfdocliente1 = new javax.swing.JFormattedTextField(mcpf);
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldnomecliente3 = new javax.swing.JTextField();
        jFormattedTextFieldcpfdocliente3 = new javax.swing.JFormattedTextField(mcpf);
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldnomecliente4 = new javax.swing.JTextField();
        jFormattedTextFieldcpfdocliente4 = new javax.swing.JFormattedTextField(mcpf);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonverificapedido = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFielddatapedido = new javax.swing.JFormattedTextField(mdata);
        jLabel9 = new javax.swing.JLabel();
        jComboBoxformaspagamento = new javax.swing.JComboBox<>();
        jTextFieldnumPedido = new javax.swing.JTextField();
        jButtonverificacliente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldnomecliente = new javax.swing.JTextField();
        jButtonverificavendedor = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldnomevendedor = new javax.swing.JTextField();
        jButtonverificaproduto = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldnomeproduto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldqtdvendida = new javax.swing.JTextField();
        jButtoninseriritem = new javax.swing.JButton();
        jButtonremoveritem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablepedido = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldqtditenspedidos = new javax.swing.JTextField();
        jTextFieldvalTotalPedido = new javax.swing.JTextField();
        jButtonsair = new javax.swing.JButton();
        jButtoninsert = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jButtonalterar = new javax.swing.JButton();
        jComboBoxprodutos = new javax.swing.JComboBox<>();
        jFormattedTextFieldcpfcliente = new javax.swing.JFormattedTextField(mcpf);
        jFormattedTextFieldcpfvendedor = new javax.swing.JFormattedTextField(mcpf);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fatec/poo/View/icons/Consultar.png"))); // NOI18N
        jButton3.setText("Consultar");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Dados Cliente");

        jLabel13.setText("CPF do Cliente");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fatec/poo/View/icons/Consultar.png"))); // NOI18N
        jButton5.setText("Consultar");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Dados Vendedor");

        jLabel17.setText("CPF do Vendedor");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fatec/poo/View/icons/Consultar.png"))); // NOI18N
        jButton6.setText("Consultar");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Dados Vendedor");

        jLabel19.setText("CPF do Vendedor");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Pedido");

        jLabel7.setText("Número do Pedido");

        jButtonverificapedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fatec/poo/View/icons/Consultar.png"))); // NOI18N
        jButtonverificapedido.setText("Consultar");
        jButtonverificapedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonverificapedidoActionPerformed(evt);
            }
        });

        jLabel8.setText("Data do Pedido");

        jFormattedTextFielddatapedido.setEnabled(false);
        jFormattedTextFielddatapedido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFielddatapedidoFocusLost(evt);
            }
        });

        jLabel9.setText("Forma de Pagamento");
        jLabel9.setEnabled(false);

        jComboBoxformaspagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A vista", "Parcelado", " " }));
        jComboBoxformaspagamento.setEnabled(false);

        jButtonverificacliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fatec/poo/View/icons/Consultar.png"))); // NOI18N
        jButtonverificacliente.setText("Consultar");
        jButtonverificacliente.setEnabled(false);
        jButtonverificacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonverificaclienteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Dados Cliente");

        jLabel11.setText("CPF do Cliente");

        jTextFieldnomecliente.setEnabled(false);

        jButtonverificavendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fatec/poo/View/icons/Consultar.png"))); // NOI18N
        jButtonverificavendedor.setText("Consultar");
        jButtonverificavendedor.setEnabled(false);
        jButtonverificavendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonverificavendedorActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Dados Vendedor");

        jLabel15.setText("CPF do Vendedor");

        jTextFieldnomevendedor.setEnabled(false);

        jButtonverificaproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fatec/poo/View/icons/Consultar.png"))); // NOI18N
        jButtonverificaproduto.setText("Consultar");
        jButtonverificaproduto.setEnabled(false);
        jButtonverificaproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonverificaprodutoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Itens do Pedido");

        jLabel21.setText("Código do Produto");

        jTextFieldnomeproduto.setEnabled(false);

        jLabel1.setText("Qtde.Vendida");
        jLabel1.setEnabled(false);

        jTextFieldqtdvendida.setEnabled(false);
        jTextFieldqtdvendida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldqtdvendidaFocusLost(evt);
            }
        });
        jTextFieldqtdvendida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldqtdvendidaKeyTyped(evt);
            }
        });

        jButtoninseriritem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fatec/poo/View/icons/Inserir.png"))); // NOI18N
        jButtoninseriritem.setText("Inserir Item");
        jButtoninseriritem.setEnabled(false);
        jButtoninseriritem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninseriritemActionPerformed(evt);
            }
        });

        jButtonremoveritem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fatec/poo/View/icons/Remover.png"))); // NOI18N
        jButtonremoveritem.setText("Remover Item");
        jButtonremoveritem.setEnabled(false);
        jButtonremoveritem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonremoveritemActionPerformed(evt);
            }
        });

        jScrollPane1.setEnabled(false);

        jTablepedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Prec.Unit", "Qtde.Vendida", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTablepedido);

        jLabel2.setText("Quantidade de Itens Pedidos");

        jLabel3.setText("Valor Total do Pedido");

        jTextFieldqtditenspedidos.setEnabled(false);

        jTextFieldvalTotalPedido.setEnabled(false);

        jButtonsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Sair.png"))); // NOI18N
        jButtonsair.setText("Sair");
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });

        jButtoninsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Inserir.png"))); // NOI18N
        jButtoninsert.setText("Inserir");
        jButtoninsert.setEnabled(false);
        jButtoninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninsertActionPerformed(evt);
            }
        });

        jButtondelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Remover.png"))); // NOI18N
        jButtondelete.setText("Excluir");
        jButtondelete.setEnabled(false);
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jButtonalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Alterar.png"))); // NOI18N
        jButtonalterar.setText("Alterar");
        jButtonalterar.setEnabled(false);
        jButtonalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonalterarActionPerformed(evt);
            }
        });

        jComboBoxprodutos.setEnabled(false);

        jFormattedTextFieldcpfcliente.setEnabled(false);

        jFormattedTextFieldcpfvendedor.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jButtoninseriritem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonremoveritem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldvalTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldqtditenspedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtoninsert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonalterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonsair, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel15))
                                        .addGap(19, 19, 19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(14, 14, 14)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldnumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jFormattedTextFieldcpfvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFormattedTextFieldcpfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonverificapedido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFielddatapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxformaspagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonverificaproduto)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButtonverificavendedor)
                                                    .addGap(46, 46, 46)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jTextFieldnomevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jTextFieldnomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jLabel1)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jTextFieldqtdvendida, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButtonverificacliente)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jTextFieldnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(0, 48, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtoninseriritem, jButtonremoveritem});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButtonverificapedido)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextFielddatapedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxformaspagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonverificacliente)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldcpfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jButtonverificavendedor)
                    .addComponent(jTextFieldnomevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldcpfvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldnomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldqtdvendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jButtonverificaproduto)
                        .addComponent(jComboBoxprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoninseriritem)
                    .addComponent(jButtonremoveritem))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldvalTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldqtditenspedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoninsert)
                    .addComponent(jButtonalterar)
                    .addComponent(jButtondelete)
                    .addComponent(jButtonsair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldqtdvendidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldqtdvendidaKeyTyped
       char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldqtdvendidaKeyTyped

    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonsairActionPerformed

    private void jButtoninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoninsertActionPerformed
        String tot = jTextFieldvalTotalPedido.getText();
        tot = tot.replaceAll("R$", "");
        tot = tot.replaceAll(",", "");
        double d = Double.parseDouble(tot);
        if(jFormattedTextFieldcpfcliente.getText().equals("") || jFormattedTextFieldcpfvendedor.getText().equals("") || jTextFieldqtditenspedidos.getText().equals("0.0") 
            || jFormattedTextFielddatapedido.getText().equals("") || jTextFieldqtditenspedidos.getText().equals("") || jTextFieldvalTotalPedido.getText().equals("0.0") || jTextFieldvalTotalPedido.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Para fazer um pedido todos os dados devem ser preenchidos e a tabela nao pode ser vazia.");
            return;
        }
        if(limite < d){
            JOptionPane.showMessageDialog(null, "Valor de compra acima do limite do cliente");
        }else{
            cadastroPedido.add(pedido);
            limite = limite - Double.parseDouble(jTextFieldvalTotalPedido.getText());
            ((Cliente)cadastro.get(posFuncPessoaC)).setLimiteDisponivel(limite);
            alteraComponentes();
            i = 0;
        }    
    }//GEN-LAST:event_jButtoninsertActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        if(posFuncPedido >= 0){
            cadastroPedido.get(posFuncPedido).getCliente().setLimiteDisponivel(Double.parseDouble(jTextFieldvalTotalPedido.getText()) + cadastroPedido.get(posFuncPedido).getCliente().getLimiteDisponivel());
            cadastroPedido.get(posFuncPedido).getCliente().removePedido(cadastroPedido.get(posFuncPedido));
            cadastroPedido.get(posFuncPedido).getVendedor().removePedido(cadastroPedido.get(posFuncPedido));
            for(int y = 0; y < cadastroPedido.get(posFuncPedido).getItens_pedidos().size();y++){
                    cadastroPedido.get(posFuncPedido).getItens_pedidos().get(y).getProduto().setQtdeEstoque(
                    cadastroPedido.get(posFuncPedido).getItens_pedidos().get(y).getQtdeVendida() + cadastroPedido.get(posFuncPedido).getItens_pedidos().get(y).getProduto().getQtdeEstoque());
                    cadastroPedido.get(posFuncPedido).removeItem(cadastroPedido.get(posFuncPedido).getItens_pedidos().get(y));
            }
            cadastroPedido.remove(posFuncPedido);
        }
        alteraComponentes();
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jButtonalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonalterarActionPerformed
    jTextFieldnumPedido.setEnabled(false);
    jButtonverificapedido.setEnabled(false);
    jFormattedTextFieldcpfcliente.setEnabled(false);
    jButtonverificacliente.setEnabled(false);
    jFormattedTextFieldcpfvendedor.setEnabled(false);
    jButtonverificavendedor.setEnabled(false);
    jComboBoxprodutos.setEnabled(false);
    jButtonverificaproduto.setEnabled(false);
    jTextFieldqtditenspedidos.setEnabled(false);
    jTextFieldvalTotalPedido.setEnabled(false);
    jButtoninsert.setEnabled(false);
    jButtondelete.setEnabled(false);
    
    jFormattedTextFielddatapedido.setEnabled(true);
    jComboBoxformaspagamento.setEnabled(true);
    jTextFieldqtdvendida.setEnabled(true);
    jButtoninseriritem.setEnabled(true);
    jButtonremoveritem.setEnabled(true);
    jButtonalterar.setEnabled(true);
    jButtonsair.setEnabled(true);
    jTablepedido.setEnabled(false);
    
    double qtde = cadastroProd.get(posFuncProd).getQtdeEstoque() - Double.parseDouble(jTextFieldqtdvendida.getText());
    
    if(jFormattedTextFielddatapedido.getText().equals("") || jTextFieldqtdvendida.getText().equals("")
        || jTextFieldnomecliente.getText().equals("") || jTextFieldnomevendedor.getText().equals("")
        || jTextFieldnomeproduto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
    }
    else if(qtde > cadastroProd.get(posFuncProd).getQtdeEstoque()){
        JOptionPane.showMessageDialog(null, "Quantidade não disponível");
    }
    else{
        cadastroPedido.get(posFuncPedido).setDataPagamento(jFormattedTextFielddatapedido.getText());
        cadastroPedido.get(posFuncPedido).setFormaPagamento((boolean) jComboBoxformaspagamento.getSelectedItem());
        cadastroProd.get(posFuncProd).setQtdeEstoque(qtde);
        cadastroPedido.get(posFuncPedido).getCliente().setLimiteDisponivel(cadastroPedido.get(posFuncPedido).getCliente().getLimiteCredito() - Double.parseDouble(jTextFieldvalTotalPedido.getText()));
        alteraComponentes();
    }
    }//GEN-LAST:event_jButtonalterarActionPerformed

    private void jButtoninseriritemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoninseriritemActionPerformed
        DecimalFormat Formato  = new DecimalFormat("#0.0"); 
        DefaultTableModel modTblPedido = (DefaultTableModel)jTablepedido.getModel();
        String preco = String.valueOf(cadastroProd.get(posFuncProd).getPreco());
        int qtde = Integer.parseInt(jTextFieldqtdvendida.getText());
        modTblPedido.setRowCount(i);
        i++;
        double prec = cadastroProd.get(posFuncProd).getPreco() * qtde;
        String s = String.valueOf(prec);
        String p = String.valueOf(prec);
        String Linha[] = {cadastroProd.get(posFuncProd).getCodigo(),cadastroProd.get(posFuncProd).getDescricao(),
        preco,jTextFieldqtdvendida.getText(),s};
        modTblPedido.addRow(Linha);
        calcularTotalitens();
        calcularTotalsubtotal();
        jTextFieldqtdvendida.setEnabled(false);
        jTextFieldqtdvendida.setText(null);
        jTextFieldnomeproduto.setText(null);
        jComboBoxprodutos.setSelectedIndex(0);
        jButtoninseriritem.setEnabled(false);
    }//GEN-LAST:event_jButtoninseriritemActionPerformed
     
    private void jButtonverificapedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonverificapedidoActionPerformed
        int x;
            for(x = 0; x < cadastroPedido.size();x++){
                    if(cadastroPedido.get(x).getNumeroPedido().equals(jTextFieldnumPedido.getText())){
                        break;
                    }
                }
                if (x < cadastroPedido.size()){
                    posFuncPedido = x; 
                }else{
                    posFuncPedido = -1;
                }
        if(posFuncPedido >= 0){
            jButtonalterar.setEnabled(true);
            jButtondelete.setEnabled(true);
            jButtoninsert.setEnabled(false);
            jButtonverificapedido.setEnabled(false);
            jButtoninseriritem.setEnabled(true);
            jButtonremoveritem.setEnabled(true);
            jFormattedTextFieldcpfcliente.setText(cadastroPedido.get(posFuncPedido).getCliente().getCpf());
            jTextFieldnomecliente.setText(cadastroPedido.get(posFuncPedido).getCliente().getNome());
            jFormattedTextFieldcpfvendedor.setEnabled(false);
            jFormattedTextFieldcpfcliente.setEnabled(false);
            jComboBoxprodutos.setEnabled(true);
            jFormattedTextFieldcpfvendedor.setText(cadastroPedido.get(posFuncPedido).getVendedor().getCpf());
            jTextFieldnomevendedor.setText(cadastroPedido.get(posFuncPedido).getVendedor().getNome());
            jFormattedTextFielddatapedido.setText(cadastroPedido.get(posFuncPedido).getDataEmissao());
            listarItens();
            calcularTotalitens();
            calcularTotalsubtotal();
        }
        else{
            jFormattedTextFielddatapedido.setEnabled(true);
            jButtonverificapedido.setEnabled(false);
            jTextFieldnumPedido.setEnabled(false);
            jButtonalterar.setEnabled(false);
            jButtondelete.setEnabled(false);
            jButtoninsert.setEnabled(true);
        }       
    }//GEN-LAST:event_jButtonverificapedidoActionPerformed

    private void jButtonverificaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonverificaclienteActionPerformed
        int x;
                for(x = 0; x < cadastro.size();x++){
                    if(cadastro.get(x).getCpf().equals(jFormattedTextFieldcpfcliente.getText()) && cadastro.get(x) instanceof Cliente){
                        break;
                    }
                }
                if (x < cadastro.size()){
                    posFuncPessoaC = x; 
                }else{
                    posFuncPessoaC = -1;
                }
                if(posFuncPessoaC >= 0){
                    
                    ((Cliente)cadastro.get(posFuncPessoaC)).addPedido(pedido);
                    limite = ((Cliente)cadastro.get(posFuncPessoaC)).getLimiteDisponivel();
                    jTextFieldnomecliente.setText(cadastro.get(posFuncPessoaC).getNome());
                    jButtonverificavendedor.setEnabled(true);
                    jFormattedTextFieldcpfcliente.setEnabled(false);
                    jFormattedTextFieldcpfvendedor.setEnabled(true);
                    jFormattedTextFielddatapedido.setEnabled(false);
                    jComboBoxformaspagamento.setEnabled(false);
                    jButtonverificacliente.setEnabled(false);
                }
                else{
                    JOptionPane.showMessageDialog(null, "CPF nao encontrado");
                }
    }//GEN-LAST:event_jButtonverificaclienteActionPerformed

    private void jButtonverificavendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonverificavendedorActionPerformed
                int x;
                
                for(x = 0; x < cadastro.size();x++){
                    if(cadastro.get(x).getCpf().equals(jFormattedTextFieldcpfvendedor.getText()) && cadastro.get(x) instanceof Vendedor){
                        break;
                    }
                }
                if (x < cadastro.size()){
                    posFuncPessoaV = x; 
                }else{
                    posFuncPessoaV = -1;
                }
                if(posFuncPessoaV >= 0){
                    ((Vendedor)cadastro.get(posFuncPessoaV)).addPedido(pedido);
                    jTextFieldnomevendedor.setText(cadastro.get(posFuncPessoaV).getNome());
                    jButtonverificavendedor.setEnabled(false);
                    jFormattedTextFieldcpfvendedor.setEnabled(false);
                    jComboBoxprodutos.setEnabled(true);
                    jButtonverificaproduto.setEnabled(true);
                    
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "CPF nao encontrado");
                }
                
    }//GEN-LAST:event_jButtonverificavendedorActionPerformed

    private void jButtonverificaprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonverificaprodutoActionPerformed
        int x;
        String cod = (String) jComboBoxprodutos.getSelectedItem();
                for(x = 0; x < cadastroProd.size();x++){
                    if(cadastroProd.get(x).getCodigo().equals(cod)){
                        break;
                    }
                }
                if (x < cadastroProd.size()){
                    posFuncProd = x; 
                }else{
                    posFuncProd = -1;
                }
                
            if(posFuncProd >= 0){
                jTextFieldqtdvendida.setEnabled(true);
                jButtonremoveritem.setEnabled(true);
                jTextFieldnomeproduto.setText(cadastroProd.get(posFuncProd).getDescricao());
            }
            else{
                JOptionPane.showMessageDialog(null, "Produto não encontrado");
            }
    }//GEN-LAST:event_jButtonverificaprodutoActionPerformed

    private void jButtonremoveritemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonremoveritemActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTablepedido.getModel();
        if (jTablepedido.getSelectedRow() >= 0){
            int x = jTablepedido.getSelectedRow();
            Object cod = jTablepedido.getValueAt(x, 0);
            Object qtd = jTablepedido.getValueAt(x, 3);
            modelo.removeRow(jTablepedido.getSelectedRow());
            jTablepedido.setModel(modelo);
            String c = String.valueOf(cod);
            String q = String.valueOf(qtd);
            Double qtde = Double.parseDouble(q);
            devolveItens(c, qtde);
        }
        else{
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        }
        i--;
        calcularTotalitens();
        calcularTotalsubtotal();
    }//GEN-LAST:event_jButtonremoveritemActionPerformed

    private void jFormattedTextFielddatapedidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFielddatapedidoFocusLost
        boolean dataValida,pagamento;
            dataValida = validarData(jFormattedTextFielddatapedido.getText());
            if(dataValida == false){
                JOptionPane.showMessageDialog(null, "Data Inválida.");
            }
            else{
                jComboBoxformaspagamento.setEnabled(true);
                pedido = new Pedido(jTextFieldnumPedido.getText(),jFormattedTextFielddatapedido.getText());

                int p = jComboBoxformaspagamento.getSelectedIndex();
                if(p == 0){
                    pagamento = false;
                }
                else{
                    pagamento = true;
                }
                pedido.setFormaPagamento(pagamento);
                jFormattedTextFieldcpfcliente.setEnabled(true);
                jButtonverificacliente.setEnabled(true);
            }      
    }//GEN-LAST:event_jFormattedTextFielddatapedidoFocusLost

    private void jTextFieldqtdvendidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldqtdvendidaFocusLost
        int qtde = Integer.parseInt(jTextFieldqtdvendida.getText());
                if(qtde <= 0){
                    JOptionPane.showMessageDialog(null, "Quantidade nao pode ser menor ou igual a zero");
                    jButtoninseriritem.setEnabled(false);
                } 
                else if(qtde > cadastroProd.get(posFuncProd).getQtdeEstoque()){
                    jButtoninseriritem.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "Quantidade solicitada acima do que temos no estoque,quantidade deste produto no estoque: " + cadastroProd.get(posFuncProd).getQtdeEstoque());
                }
                
                else if(qtde > 0 && qtde <= cadastroProd.get(posFuncProd).getQtdeEstoque() ){
                    if(posFuncProd >= 0){
                        ItemPedido item = new ItemPedido((i + 1), qtde, cadastroProd.get(posFuncProd));
                        jButtoninseriritem.setEnabled(true);
                        pedido.addItem(item);
                        jTextFieldnomeproduto.setText(cadastroProd.get(posFuncProd).getDescricao());
                    }
            }
    }//GEN-LAST:event_jTextFieldqtdvendidaFocusLost

    public void devolveItens(String cod,double qtd){
        for(int y = 0;y < cadastroProd.size();y++){
            if(cadastroProd.get(y).getCodigo().equals(cod)){
                cadastroProd.get(y).setQtdeEstoque(cadastroProd.get(y).getQtdeEstoque() + qtd);
            }
        }
        
    }
    
    
    public boolean validarData(String data){
        try {
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            
            sdf.setLenient(false);
           
            sdf.parse(data);
            
            return true;
        } catch (ParseException ex) {
            return false;
        }
    }
    
    
   


    
    
    
    
    
    
    public void calcularTotalsubtotal(){
    //DecimalFormat df = new DecimalFormat("#,##0.00");
    double somaTotal=0;int x;
    for(x=0; x<jTablepedido.getRowCount();x++){
        Object obj = jTablepedido.getValueAt(x, 4);
        String s = String.valueOf(obj);
        s = s.replaceAll("\\.", "");
        somaTotal += Double.parseDouble(s);
    }
    String tot = String.valueOf(somaTotal/10);
    jTextFieldvalTotalPedido.setText(tot);
    
    }
    public void calcularTotalitens(){
    double somaTotal=0;int x;
    for(x=0; x<jTablepedido.getRowCount();x++){
        Object obj = jTablepedido.getValueAt(x, 3);
        String s = String.valueOf(obj);
        somaTotal += Double.parseDouble(s);
    }
        String tot = String.valueOf(somaTotal);
        jTextFieldqtditenspedidos.setText(tot);
    }
    public void listarItens(){
        DefaultTableModel modTblPedido = (DefaultTableModel)jTablepedido.getModel();
        int a = 0;
        modTblPedido.setRowCount(a);
        for(int y = 0; y < cadastroPedido.get(posFuncPedido).getItens_pedidos().size();y++){
            String Linha[] = {cadastroPedido.get(posFuncPedido).getItens_pedidos().get(y).getProduto().getCodigo(),
            cadastroPedido.get(posFuncPedido).getItens_pedidos().get(y).getProduto().getDescricao(),
            String.valueOf(cadastroPedido.get(posFuncPedido).getItens_pedidos().get(y).getProduto().getPreco()),
            String.valueOf(cadastroPedido.get(posFuncPedido).getItens_pedidos().get(y).getQtdeVendida()),
            String.valueOf(cadastroPedido.get(posFuncPedido).getItens_pedidos().get(y).getProduto().getPreco() * cadastroPedido.get(posFuncPedido).getItens_pedidos().get(y).getQtdeVendida())};
            modTblPedido.addRow(Linha);
            a++;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiEmitirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiEmitirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiEmitirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiEmitirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonalterar;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtoninseriritem;
    private javax.swing.JButton jButtoninsert;
    private javax.swing.JButton jButtonremoveritem;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JButton jButtonverificacliente;
    private javax.swing.JButton jButtonverificapedido;
    private javax.swing.JButton jButtonverificaproduto;
    private javax.swing.JButton jButtonverificavendedor;
    private javax.swing.JComboBox<String> jComboBoxformaspagamento;
    private javax.swing.JComboBox<String> jComboBoxprodutos;
    private javax.swing.JFormattedTextField jFormattedTextFieldcpfcliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldcpfdocliente1;
    private javax.swing.JFormattedTextField jFormattedTextFieldcpfdocliente3;
    private javax.swing.JFormattedTextField jFormattedTextFieldcpfdocliente4;
    private javax.swing.JFormattedTextField jFormattedTextFieldcpfvendedor;
    private javax.swing.JFormattedTextField jFormattedTextFielddatapedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablepedido;
    private javax.swing.JTextField jTextFieldnomecliente;
    private javax.swing.JTextField jTextFieldnomecliente1;
    private javax.swing.JTextField jTextFieldnomecliente3;
    private javax.swing.JTextField jTextFieldnomecliente4;
    private javax.swing.JTextField jTextFieldnomeproduto;
    private javax.swing.JTextField jTextFieldnomevendedor;
    private javax.swing.JTextField jTextFieldnumPedido;
    private javax.swing.JTextField jTextFieldqtditenspedidos;
    private javax.swing.JTextField jTextFieldqtdvendida;
    private javax.swing.JTextField jTextFieldvalTotalPedido;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Produto> cadastroProd;
    private int posFuncProd;
    private ArrayList<Pessoa> cadastro;
    private int posFuncPessoaV;
    private int posFuncPessoaC;
    private ArrayList<Pedido> cadastroPedido;
    private int posFuncPedido;
}
