/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fatec.poo.View;

import Fatec.poo.model.Produto;
import com.sun.xml.internal.ws.util.StringUtils;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author gdeba
 */
public class GuiProduto extends javax.swing.JFrame {
    MaskFormatter mdinheiro;
    /**
     * Creates new form CadastroProduto
     * @param cadProd
     */
    public GuiProduto(ArrayList <Produto> cadProd) {
        initComponents();
        cadastroProd = cadProd;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButtoninsert = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jButtonconsulta = new javax.swing.JButton();
        jButtonalterar = new javax.swing.JButton();
        jButtonsair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldcodigo = new javax.swing.JTextField();
        jTextFieldqtdestoque = new javax.swing.JTextField();
        jTextFieldestoqueminimo = new javax.swing.JTextField();
        jFormattedTextFielddescricao = new javax.swing.JFormattedTextField();
        jFormattedTextFieldpreco = new javax.swing.JFormattedTextField(mdinheiro);
        jLabel3 = new javax.swing.JLabel();
        jTextFieldunidademedida = new javax.swing.JTextField();

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Inserir.png"))); // NOI18N
        jButton6.setText("Inserir");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Remover.png"))); // NOI18N
        jButton7.setText("Excluir");

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Consultar.png"))); // NOI18N
        jButton8.setText("Consultar");

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Alterar.png"))); // NOI18N
        jButton9.setText("Alterar");

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Sair.png"))); // NOI18N
        jButton10.setText("Sair");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtoninsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Inserir.png"))); // NOI18N
        jButtoninsert.setText("Inserir");
        jButtoninsert.setEnabled(false);
        jButtoninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninsertActionPerformed(evt);
            }
        });

        jButtondelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Remover.png"))); // NOI18N
        jButtondelete.setText("Excluir");
        jButtondelete.setEnabled(false);
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jButtonconsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Consultar.png"))); // NOI18N
        jButtonconsulta.setText("Consultar");
        jButtonconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconsultaActionPerformed(evt);
            }
        });

        jButtonalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Alterar.png"))); // NOI18N
        jButtonalterar.setText("Alterar");
        jButtonalterar.setEnabled(false);
        jButtonalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonalterarActionPerformed(evt);
            }
        });

        jButtonsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Sair.png"))); // NOI18N
        jButtonsair.setText("Sair");
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Descrição");
        jLabel2.setEnabled(false);

        jLabel4.setText("Quantidade Estoque");
        jLabel4.setEnabled(false);

        jLabel5.setText("Preço");
        jLabel5.setEnabled(false);

        jLabel6.setText("Estoque Mínimo");
        jLabel6.setEnabled(false);

        jTextFieldqtdestoque.setEnabled(false);
        jTextFieldqtdestoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldqtdestoqueKeyTyped(evt);
            }
        });

        jTextFieldestoqueminimo.setEnabled(false);
        jTextFieldestoqueminimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldestoqueminimoKeyTyped(evt);
            }
        });

        jFormattedTextFielddescricao.setEnabled(false);

        jFormattedTextFieldpreco.setEnabled(false);
        jFormattedTextFieldpreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldprecoKeyTyped(evt);
            }
        });

        jLabel3.setText("Unidade de medida");
        jLabel3.setEnabled(false);

        jTextFieldunidademedida.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonconsulta)
                        .addGap(18, 18, 18)
                        .addComponent(jButtoninsert, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonsair, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFielddescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldqtdestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(49, 49, 49)
                                        .addComponent(jTextFieldestoqueminimo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldunidademedida, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonalterar, jButtonconsulta, jButtondelete, jButtoninsert, jButtonsair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFielddescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldqtdestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldestoqueminimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldunidademedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonconsulta)
                    .addComponent(jButtoninsert)
                    .addComponent(jButtonalterar)
                    .addComponent(jButtondelete)
                    .addComponent(jButtonsair))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonsairActionPerformed

    private void jButtonconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconsultaActionPerformed
        if(jTextFieldcodigo.getText().equals("")){
           JOptionPane.showMessageDialog(null, "O código nao pode ser vazio");
        }
        else{
                int i;
                for(i = 0; i < cadastroProd.size();i++){
                    if(cadastroProd.get(i).getCodigo().equals(jTextFieldcodigo.getText())){
                        break;
                    }
                }
                if(i < cadastroProd.size()){
                    posProd = i;
                }
                else {
                    posProd = -1;
                }
                if(posProd >= 0){
                    jButtonalterar.setEnabled(true);
                    jButtondelete.setEnabled(true);
                    jButtoninsert.setEnabled(false);
                    jButtonconsulta.setEnabled(false);
                    jFormattedTextFielddescricao.setText(cadastroProd.get(posProd).getDescricao());
                    String s = Double.toString(cadastroProd.get(posProd).getPreco());
                    jFormattedTextFieldpreco.setText(s);
                    String qtdeestoque = Double.toString(cadastroProd.get(posProd).getQtdeEstoque());
                    jTextFieldqtdestoque.setText(qtdeestoque);
                    String qtdeestoquemin = Double.toString(cadastroProd.get(posProd).getEstoqueMinimo());
                    jTextFieldestoqueminimo.setText(qtdeestoquemin);
                    jTextFieldunidademedida.setText(cadastroProd.get(posProd).getUniMedida());
                }
                else{
                    jButtonalterar.setEnabled(false);
                    jButtondelete.setEnabled(false);
                    jButtoninsert.setEnabled(true);
                    jButtonconsulta.setEnabled(false);
                    jFormattedTextFielddescricao.requestFocus();
                }
                jTextFieldcodigo.setEnabled(false);
                jFormattedTextFielddescricao.setEnabled(true);
                jFormattedTextFieldpreco.setEnabled(true);
                jTextFieldestoqueminimo.setEnabled(true);
                jTextFieldqtdestoque.setEnabled(true);
                jTextFieldunidademedida.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonconsultaActionPerformed

    private void jButtoninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoninsertActionPerformed
        if(jFormattedTextFielddescricao.getText().equals("") || jTextFieldestoqueminimo.getText().equals("")
                || jFormattedTextFieldpreco.getText().equals("") || jTextFieldqtdestoque.getText().equals("") || jTextFieldunidademedida.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.");
        }    
        else{
            Produto prod = new Produto(jTextFieldcodigo.getText(), StringUtils.capitalize(jFormattedTextFielddescricao.getText()));
            String estoqueMinimo = jTextFieldestoqueminimo.getText();
            prod.setEstoqueMinimo(Double.parseDouble(estoqueMinimo));
            String preco = jFormattedTextFieldpreco.getText().replace(',','.');
            prod.setPreco(Double.parseDouble(preco));
            String qtdeestoque = jTextFieldqtdestoque.getText();
            prod.setQtdeEstoque(Double.parseDouble(qtdeestoque));
            prod.setUniMedida(jTextFieldunidademedida.getText());
            cadastroProd.add(prod);
            alteracomponentes();
        }
    }//GEN-LAST:event_jButtoninsertActionPerformed

    private void jButtonalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonalterarActionPerformed
        jTextFieldcodigo.setEnabled(false);
         if(jFormattedTextFielddescricao.getText().equals("") || jTextFieldestoqueminimo.getText().equals("")
                || jFormattedTextFieldpreco.getText().equals("") || jTextFieldqtdestoque.getText().equals("") || jTextFieldunidademedida.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.");
        }    
        else{
        cadastroProd.get(posProd).setDescricao(StringUtils.capitalize(jFormattedTextFielddescricao.getText()));
        String estoqueMinimo = jTextFieldestoqueminimo.getText();
        cadastroProd.get(posProd).setEstoqueMinimo(Double.parseDouble(estoqueMinimo));
        String preco = jFormattedTextFieldpreco.getText().replace(',','.');
        cadastroProd.get(posProd).setPreco(Double.parseDouble(preco));
        String qtdeestoque = jTextFieldqtdestoque.getText();
        cadastroProd.get(posProd).setQtdeEstoque(Double.parseDouble(qtdeestoque));
        cadastroProd.get(posProd).setUniMedida(jTextFieldunidademedida.getText());
        alteracomponentes();
        }
    }//GEN-LAST:event_jButtonalterarActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        if(posProd >= 0){
            cadastroProd.remove(posProd);
            posProd--;
        }
        alteracomponentes();
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jTextFieldqtdestoqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldqtdestoqueKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldqtdestoqueKeyTyped

    private void jTextFieldestoqueminimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldestoqueminimoKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldestoqueminimoKeyTyped

    private void jFormattedTextFieldprecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldprecoKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextFieldprecoKeyTyped
    public void alteracomponentes(){
        jFormattedTextFielddescricao.setText(null);
        jFormattedTextFieldpreco.setText(null);
        jTextFieldqtdestoque.setText(null);
        jTextFieldestoqueminimo.setText(null);
        jTextFieldcodigo.setText(null);
        jFormattedTextFielddescricao.setText(null);
        jFormattedTextFieldpreco.setText(null);
        jTextFieldunidademedida.setText(null);
        jButtonalterar.setEnabled(false);
        jButtondelete.setEnabled(false);
        jButtoninsert.setEnabled(false);
        jButtonconsulta.setEnabled(true);
        jTextFieldcodigo.setEnabled(true);
        jFormattedTextFielddescricao.setEnabled(false);
        jFormattedTextFieldpreco.setEnabled(false);
        jTextFieldqtdestoque.setEnabled(false);
        jTextFieldestoqueminimo.setEnabled(false);
        jTextFieldunidademedida.setEnabled(false);
        
        jTextFieldcodigo.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonalterar;
    private javax.swing.JButton jButtonconsulta;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtoninsert;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JFormattedTextField jFormattedTextFielddescricao;
    private javax.swing.JFormattedTextField jFormattedTextFieldpreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldcodigo;
    private javax.swing.JTextField jTextFieldestoqueminimo;
    private javax.swing.JTextField jTextFieldqtdestoque;
    private javax.swing.JTextField jTextFieldunidademedida;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Produto> cadastroProd;
    private int posProd;
}
