/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fatec.poo.View;

import Fatec.poo.model.Pessoa;
import Fatec.poo.model.Vendedor;
import com.sun.xml.internal.ws.util.StringUtils;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author gdeba
 */
public class GuiVendedor extends javax.swing.JFrame {
    MaskFormatter mCEP;
    MaskFormatter mTEL;
    MaskFormatter mcpf;
    MaskFormatter mSalBase;
    /**
     * Creates new form CadastroVendedor
     */
    public GuiVendedor(ArrayList<Pessoa> cadPessoas) throws ParseException {
        mCEP = new MaskFormatter("#####-###");
        mTEL = new MaskFormatter("####-####");
        mcpf = new MaskFormatter("###.###.###-##");
        initComponents();
        cadastro = cadPessoas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jFormattedTextFieldtel = new javax.swing.JFormattedTextField(mTEL);
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField(mCEP);
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtoninsert = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButtonconsulta = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButtonalterar = new javax.swing.JButton();
        jTextFieldcpf = new javax.swing.JFormattedTextField(mcpf);
        jButtonsair = new javax.swing.JButton();
        jTextFieldnome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxddds = new javax.swing.JComboBox<>();
        jTextFieldendereco = new javax.swing.JTextField();
        jFormattedTextFieldtelefone = new javax.swing.JFormattedTextField(mTEL);
        jLabel15 = new javax.swing.JLabel();
        jTextFieldcidade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldtxcomissao = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextFieldCEP1 = new javax.swing.JFormattedTextField(mCEP);
        jLabel18 = new javax.swing.JLabel();
        jComboBoxestados = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldsalbase = new javax.swing.JTextField();

        jLabel6.setText("Estado");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Inserir.png"))); // NOI18N
        jButton1.setText("Inserir");

        jLabel7.setText("DDD");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Remover.png"))); // NOI18N
        jButton2.setText("Excluir");

        jLabel8.setText("Telefone");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Consultar.png"))); // NOI18N
        jButton3.setText("Consultar");

        jLabel9.setText("Limite de Crédito");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Alterar.png"))); // NOI18N
        jButton4.setText("Alterar");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Sair.png"))); // NOI18N
        jButton5.setText("Sair");

        jLabel1.setText("CPF");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12", "13", "14", "15", "16", "17", "18", "19", "21", "22", "24", "27", "28", "31", "32", "33", "34", "35", "37", "38", "41", "42", "43", "44", "45", "46", "47", "48", "49", "51", "53", "54", "55", "61", "62", "63", "64", "65", "66", "67", "68", "69", "71", "73", "74", "75", "77", "79", "81", "82", "83", "84", "85", "86", "87", "88", "89", "91", "92", "93", "94", "95", "96", "97", "98", "99", " " }));

        jLabel2.setText("Nome");

        jLabel3.setText("Endereço");

        jLabel4.setText("CEP");

        jFormattedTextFieldCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCEPActionPerformed(evt);
            }
        });

        jLabel5.setText("Cidade");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtoninsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Inserir.png"))); // NOI18N
        jButtoninsert.setText("Inserir");
        jButtoninsert.setEnabled(false);
        jButtoninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninsertActionPerformed(evt);
            }
        });

        jButtondelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Remover.png"))); // NOI18N
        jButtondelete.setText("Excluir");
        jButtondelete.setEnabled(false);
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jLabel12.setText("Telefone");
        jLabel12.setEnabled(false);

        jButtonconsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Consultar.png"))); // NOI18N
        jButtonconsulta.setText("Consultar");
        jButtonconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconsultaActionPerformed(evt);
            }
        });

        jLabel13.setText("Taxa de comissão(%)");
        jLabel13.setEnabled(false);

        jButtonalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Alterar.png"))); // NOI18N
        jButtonalterar.setText("Alterar");
        jButtonalterar.setEnabled(false);
        jButtonalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonalterarActionPerformed(evt);
            }
        });

        jButtonsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Sair.png"))); // NOI18N
        jButtonsair.setText("Sair");
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });

        jTextFieldnome.setEnabled(false);
        jTextFieldnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomeActionPerformed(evt);
            }
        });
        jTextFieldnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldnomeKeyTyped(evt);
            }
        });

        jLabel14.setText("CPF");

        jComboBoxddds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DDD", "11", "12", "13", "14", "15", "16", "17", "18", "19", "21", "22", "24", "27", "28", "31", "32", "33", "34", "35", "37", "38", "41", "42", "43", "44", "45", "46", "47", "48", "49", "51", "53", "54", "55", "61", "62", "63", "64", "65", "66", "67", "68", "69", "71", "73", "74", "75", "77", "79", "81", "82", "83", "84", "85", "86", "87", "88", "89", "91", "92", "93", "94", "95", "96", "97", "98", "99", " " }));
        jComboBoxddds.setEnabled(false);

        jTextFieldendereco.setEnabled(false);

        jFormattedTextFieldtelefone.setEnabled(false);

        jLabel15.setText("Nome");
        jLabel15.setEnabled(false);

        jTextFieldcidade.setEnabled(false);
        jTextFieldcidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldcidadeKeyTyped(evt);
            }
        });

        jLabel16.setText("Endereço");
        jLabel16.setEnabled(false);

        jTextFieldtxcomissao.setEnabled(false);
        jTextFieldtxcomissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtxcomissaoActionPerformed(evt);
            }
        });
        jTextFieldtxcomissao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldtxcomissaoKeyTyped(evt);
            }
        });

        jLabel17.setText("CEP");
        jLabel17.setEnabled(false);

        jFormattedTextFieldCEP1.setEnabled(false);
        jFormattedTextFieldCEP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCEP1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Cidade");
        jLabel18.setEnabled(false);

        jComboBoxestados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UF", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboBoxestados.setEnabled(false);
        jComboBoxestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxestadosActionPerformed(evt);
            }
        });

        jLabel19.setText("Salário Base");
        jLabel19.setEnabled(false);

        jTextFieldsalbase.setEnabled(false);
        jTextFieldsalbase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldsalbaseKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxestados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jFormattedTextFieldtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxddds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addGap(4, 4, 4)
                                .addComponent(jFormattedTextFieldCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldtxcomissao, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldsalbase, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButtoninsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonalterar))
                    .addComponent(jButtonconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonsair, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonalterar, jButtonconsulta, jButtondelete, jButtoninsert, jButtonsair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxestados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel12)
                        .addComponent(jComboBoxddds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFormattedTextFieldCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldtxcomissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldsalbase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoninsert)
                    .addComponent(jButtonalterar)
                    .addComponent(jButtonconsulta)
                    .addComponent(jButtondelete)
                    .addComponent(jButtonsair))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCEPActionPerformed

    private void jFormattedTextFieldCEP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCEP1ActionPerformed

    private void jTextFieldnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnomeActionPerformed

    private void jComboBoxestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxestadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxestadosActionPerformed

    private void jTextFieldtxcomissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtxcomissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtxcomissaoActionPerformed

    private void jButtonconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconsultaActionPerformed
        boolean valido = Pessoa.verificaCPF(jTextFieldcpf.getText());
        if(valido == false){
            JOptionPane.showMessageDialog(null, "CPF inválido");
            jTextFieldcpf.setText(null);
        }
        else{
                int x;
                for(x = 0; x < cadastro.size();x++){
                    if(cadastro.get(x).getCpf().equals(jTextFieldcpf.getText()) && cadastro.get(x) instanceof Vendedor){
                        break;
                    }
                }
                if (x < cadastro.size()){
                    posPessoa = x; //localizou o objeto Funcionario (horista, mensalista ou comissionado) no ArrayList
                }else{
                    posPessoa = -1;//não localizou o objeto Projeto no ArrayList
                }

                if(posPessoa >= 0){
                    jTextFieldnome.setEnabled(false);
                    jButtonalterar.setEnabled(true);
                    jButtondelete.setEnabled(true);
                    jButtoninsert.setEnabled(false);
                    jButtonconsulta.setEnabled(false);
                    jTextFieldnome.setText(cadastro.get(posPessoa).getNome());
                    jTextFieldendereco.setText(cadastro.get(posPessoa).getEndereco());
                    jTextFieldcidade.setText(cadastro.get(posPessoa).getCidade());
                    jFormattedTextFieldCEP1.setText(cadastro.get(posPessoa).getCep());
                    jFormattedTextFieldtelefone.setText(cadastro.get(posPessoa).getTelefone());
                    jTextFieldtxcomissao.setText(String.valueOf(((Vendedor)cadastro.get(posPessoa)).getTaxaComissao()));
                    jTextFieldsalbase.setText(String.valueOf(((Vendedor)cadastro.get(posPessoa)).getSalBase()));
                    jComboBoxestados.getModel().setSelectedItem(cadastro.get(posPessoa).getUf());
                    jComboBoxddds.getModel().setSelectedItem(cadastro.get(posPessoa).getDdd());
                }
                else{
                    jButtonalterar.setEnabled(false);
                    jButtondelete.setEnabled(false);
                    jButtoninsert.setEnabled(true);
                    jButtonconsulta.setEnabled(false);
                    jTextFieldnome.requestFocus();
                }
                jTextFieldnome.setEnabled(true);
                jTextFieldsalbase.setEnabled(true);
                jTextFieldcpf.setEnabled(false);
                jTextFieldcidade.setEnabled(true);
                jTextFieldendereco.setEnabled(true);
                jFormattedTextFieldCEP1.setEnabled(true);
                jFormattedTextFieldtelefone.setEnabled(true);
                jTextFieldtxcomissao.setEnabled(true);
                jComboBoxestados.setEnabled(true);
                jComboBoxddds.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonconsultaActionPerformed

    private void jButtoninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoninsertActionPerformed
        String ddd = (String)jComboBoxddds.getSelectedItem();
        String uf = (String) jComboBoxestados.getSelectedItem();
        if(jTextFieldnome.getText().equals("") || jTextFieldcidade.getText().equals("") || jTextFieldendereco.getText().equals("") || 
                jTextFieldsalbase.getText().equals("") || jTextFieldtxcomissao.getText().equals("") || jFormattedTextFieldCEP1.getText().equals("     -   ")
                || jFormattedTextFieldtelefone.getText().equals("    -    ") || uf.equalsIgnoreCase("uf") || ddd.equals("DDD")){
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos e um estado e um ddd devem ser selecionados");
        }
        else{
        Pessoa pessoa = null;
        Double salBase = Double.parseDouble(jTextFieldsalbase.getText().replace(',', '.'));
        
        pessoa = new Vendedor(jTextFieldcpf.getText(),StringUtils.capitalize(jTextFieldnome.getText()),salBase);
        Double tx = Double.parseDouble(jTextFieldtxcomissao.getText().replace(',', '.'));
        ((Vendedor)pessoa).setTaxaComissao(tx);
        pessoa.setUf(String.valueOf(jComboBoxestados.getSelectedItem()));
        pessoa.setCep(jFormattedTextFieldCEP1.getText());
        pessoa.setTelefone(jFormattedTextFieldtelefone.getText());
        pessoa.setCidade(StringUtils.capitalize(jTextFieldcidade.getText()));
        pessoa.setDdd(String.valueOf(jComboBoxddds.getSelectedItem()));
        pessoa.setEndereco(StringUtils.capitalize(jTextFieldendereco.getText()));
        cadastro.add(pessoa);
        alteracomponentes();
        }
        
        
    }//GEN-LAST:event_jButtoninsertActionPerformed
    
    
    public void alteracomponentes(){
        jTextFieldendereco.setText(null);
        jFormattedTextFieldCEP1.setText(null);
        jFormattedTextFieldtelefone.setText(null);
        jTextFieldcidade.setText(null);
        jTextFieldcpf.setText(null);
        jTextFieldnome.setText(null);
        jTextFieldsalbase.setText(null);
        jTextFieldtxcomissao.setText(null);
        jComboBoxddds.setSelectedIndex(0);
        jComboBoxestados.setSelectedIndex(0);
        jButtonalterar.setEnabled(false);
        jButtondelete.setEnabled(false);
        jButtoninsert.setEnabled(false);
        jButtonconsulta.setEnabled(true);
        jTextFieldcpf.setEnabled(true);
        jTextFieldendereco.setText(null);
        jFormattedTextFieldCEP1.setText(null);
        jFormattedTextFieldtelefone.setText(null);
        jTextFieldcidade.setEnabled(false);
        jTextFieldnome.setEnabled(false);
        jTextFieldsalbase.setEnabled(false);
        jTextFieldtxcomissao.setEnabled(false);
        jComboBoxddds.setEnabled(false);
        jComboBoxestados.setEnabled(false);
        jFormattedTextFieldCEP1.setEnabled(false);
        jFormattedTextFieldtelefone.setEnabled(false);
        jTextFieldendereco.setEnabled(false);
        jTextFieldcpf.requestFocus();
    }
    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonsairActionPerformed

    private void jButtonalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonalterarActionPerformed
        jTextFieldcpf.setEnabled(false);
        
        String ddd = (String)jComboBoxddds.getSelectedItem();
        String uf = (String) jComboBoxestados.getSelectedItem();
        if(jTextFieldnome.getText().equals("") || jTextFieldcidade.getText().equals("") || jTextFieldendereco.getText().equals("") || 
                jTextFieldsalbase.getText().equals("") || jTextFieldtxcomissao.getText().equals("") || jFormattedTextFieldCEP1.getText().equals("     -   ")
                || jFormattedTextFieldtelefone.getText().equals("    -    ") || uf.equalsIgnoreCase("uf") || ddd.equals("DDD")){
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos e um estado e um ddd devem ser selecionados");
        }
        else{
        cadastro.get(posPessoa).setNome(StringUtils.capitalize(jTextFieldnome.getText()));
        ((Vendedor)cadastro.get(posPessoa)).setSalBase(Double.parseDouble(jTextFieldsalbase.getText().replace(',', '.')));
        cadastro.get(posPessoa).setCep(jFormattedTextFieldCEP1.getText());
        cadastro.get(posPessoa).setCidade(StringUtils.capitalize(jTextFieldcidade.getText()));
        cadastro.get(posPessoa).setEndereco(StringUtils.capitalize(jTextFieldendereco.getText()));
        cadastro.get(posPessoa).setTelefone(jFormattedTextFieldtelefone.getText());
        ((Vendedor)cadastro.get(posPessoa)).setTaxaComissao(Double.parseDouble(jTextFieldtxcomissao.getText().replace(',', '.')));
        cadastro.get(posPessoa).setUf(String.valueOf(jComboBoxestados.getSelectedItem()));
        cadastro.get(posPessoa).setDdd(String.valueOf(jComboBoxddds.getSelectedItem()));
        alteracomponentes();
        }
    }//GEN-LAST:event_jButtonalterarActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        if(posPessoa >= 0){
            cadastro.remove(posPessoa);
            posPessoa--;
        }
        alteracomponentes();
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jTextFieldsalbaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldsalbaseKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldsalbaseKeyTyped

    private void jTextFieldcidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldcidadeKeyTyped
        String caracteres = "0987654321";
        
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldcidadeKeyTyped

    private void jTextFieldtxcomissaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldtxcomissaoKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldtxcomissaoKeyTyped

    private void jTextFieldnomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnomeKeyTyped
        String caracteres = "0987654321";
        
        if(caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldnomeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonalterar;
    private javax.swing.JButton jButtonconsulta;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtoninsert;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxddds;
    private javax.swing.JComboBox<String> jComboBoxestados;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP1;
    private javax.swing.JFormattedTextField jFormattedTextFieldtel;
    private javax.swing.JFormattedTextField jFormattedTextFieldtelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldcidade;
    private javax.swing.JTextField jTextFieldcpf;
    private javax.swing.JTextField jTextFieldendereco;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldsalbase;
    private javax.swing.JTextField jTextFieldtxcomissao;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pessoa> cadastro;
    private int posPessoa;
}
